backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "게시글"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "제목"
        name: "title"
        widget: "string"
      
      - label: "게시일"
        name: "date"
        widget: "datetime"
      
      - label: "1차 카테고리"
        name: "category"
        widget: "select"
        options:
          - { label: "웹 디자인", value: "web_design" }
          - { label: "컨텐츠 디자인", value: "content_design" }
          - { label: "영상 디자인", value: "video_design" }
          - { label: "광고/인쇄 디자인", value: "ad_print_design" }
      
      - label: "2차 카테고리"
        name: "subcategory"
        widget: "select"
        options:
          - label: "웹 디자인"
            options:
              - { label: "홈페이지", value: "homepage" }
              - { label: "디지털배너", value: "digital_banner" }
              - { label: "상세페이지", value: "detail_page" }
              - { label: "UX/UI", value: "ux_ui" }
              - { label: "기타 (웹디자인)", value: "web_design_etc" }
          
          - label: "컨텐츠 디자인"
            options:
              - { label: "카드뉴스", value: "card_news" }
              - { label: "포스터", value: "poster" }
              - { label: "SNS이미지", value: "sns_image" }
              - { label: "피드광고", value: "feed_ad" }
              - { label: "기타 (컨텐츠)", value: "content_etc" }
          
          - label: "영상 디자인"
            options:
              - { label: "영상 제작", value: "video_production" }
              - { label: "영상 편집", value: "video_editing" }
              - { label: "모션그래픽", value: "motion_graphic" }
              - { label: "유튜브 썸네일", value: "youtube_thumbnail" }
          
          - label: "광고/인쇄 디자인"
            options:
              - { label: "현수막/엑스배너", value: "banner_x_banner" }
              - { label: "명함", value: "business_card" }
              - { label: "브로슈어/카탈로그", value: "brochure_catalog" }
              - { label: "옥외광고", value: "outdoor_ad" }
              - { label: "소식", value: "news" }
      
      - label: "설명"
        name: "description"
        widget: "text"
        required: false
      
      - label: "썸네일 이미지"
        name: "thumbnail"
        widget: "image"
      
      - label: "본문 이미지"
        name: "body_image"
        widget: "image"
        required: false
      
      - label: "본문 내용"
        name: "body"
        widget: "markdown"