backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "게시글"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "제목"
        name: "title"
        widget: "string"
      
      - label: "게시일"
        name: "date"
        widget: "datetime"
      
      - label: "1차 카테고리"
        name: "category"
        widget: "select"
        options:
          - { label: "웹 디자인", value: "web" }
          - { label: "컨텐츠 디자인", value: "contentn" }
          - { label: "영상 디자인", value: "video" }
          - { label: "광고/인쇄 디자인", value: "ad" }
      
      - label: "2차 카테고리"
        name: "subcategory"
        widget: "select"
        options:
          - { label: "홈페이지", value: "homepage", group: "웹 디자인" }
          - { label: "디지털배너", value: "digital_banner", group: "웹 디자인" }
          - { label: "상세페이지", value: "detail_page", group: "웹 디자인" }
          - { label: "UX/UI", value: "ux_ui", group: "웹 디자인" }
          - { label: "기타 (웹디자인)", value: "web_design_etc", group: "웹 디자인" }
          
          - { label: "카드뉴스", value: "card_news", group: "컨텐츠 디자인" }
          - { label: "포스터", value: "poster", group: "컨텐츠 디자인" }
          - { label: "SNS이미지", value: "sns_image", group: "컨텐츠 디자인" }
          - { label: "피드광고", value: "feed_ad", group: "컨텐츠 디자인" }
          - { label: "기타 (컨텐츠)", value: "content_etc", group: "컨텐츠 디자인" }
          
          - { label: "영상 제작", value: "video_production", group: "영상 디자인" }
          - { label: "영상 편집", value: "video_editing", group: "영상 디자인" }
          - { label: "모션그래픽", value: "motion_graphic", group: "영상 디자인" }
          - { label: "유튜브 썸네일", value: "youtube_thumbnail", group: "영상 디자인" }
          
          - { label: "현수막/엑스배너", value: "banner_x_banner", group: "광고/인쇄 디자인" }
          - { label: "명함", value: "business_card", group: "광고/인쇄 디자인" }
          - { label: "브로슈어/카탈로그", value: "brochure_catalog", group: "광고/인쇄 디자인" }
          - { label: "옥외광고", value: "outdoor_ad", group: "광고/인쇄 디자인" }
          - { label: "소식", value: "news", group: "광고/인쇄 디자인" }
      
      - label: "설명"
        name: "description"
        widget: "text"
        required: false
      
      - label: "이미지 갤러리"
        name: "images"
        widget: "list"
        summary: "{{fields.image}}"
        field:
          label: 이미지
          name: image
          widget: image
        hint: "여러 이미지를 추가할 수 있습니다. 첫 번째 이미지가 썸네일로 사용됩니다."
      
      - label: "본문 내용"
        name: "body"
        widget: "markdown"